CREATE DATABASE powernode;

USE powernode;

CREATE TABLE t_car 
AS 
SELECT * FROM mybatis.t_car
WHERE 1=2

SELECT * FROM t_car;

DROP TABLE t_car

SHOW CREATE TABLE t_car

ALTER TABLE t_car
MODIFY id BIGINT PRIMARY KEY AUTO_INCREMENT


CREATE TABLE t_act(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
actno VARCHAR(255),
balance DECIMAL(15,2)
);

INSERT INTO t_act
VALUES(NULL,'act001',50000.00),
(NULL,'act002',0.00)

SELECT * FROM t_act